CREATE TABLE REMOTE_SYSTEM (
	SYSTEM_ID VARCHAR(100) PRIMARY KEY
	,CHECKER_TYPE VARCHAR(100)
	,CONNECTION_STRING VARCHAR(600)
	,HINTS VARCHAR(MAX)
	,CHECK_PERIOD INT
	,PERIOD_UNIT VARCHAR(15)
	,DISABLED CHAR(1)
)

CREATE TABLE NOTIFICATION (
	SYSTEM_ID VARCHAR(100)
	,NOTIFY_TYPE VARCHAR(50)
	,USER_GROUP VARCHAR(50)
	,LEVEL VARCHAR(50)
	,PRIMARY KEY (SYSTEM_ID, NOTIFY_TYPE, USER_GROUP)
)

CREATE TABLE USER_INFO (
	USER_ID VARCHAR(50) PRIMARY KEY
	,USER_NAME VARCHAR(100)
)

CREATE TABLE USER_GROUP (
	GROUP_ID VARCHAR(50) PRIMARY KEY
	,GROUP_NAME VARCHAR(100)
)

CREATE TABLE GROUP_MEMBER (
	GROUP_ID VARCHAR(50)
	,USER_ID VARCHAR(50)
	,PRIMARY KEY (GROUP_ID, USER_ID)
)

